// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

public interface RpcDataListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.RpcDataList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .core.RpcValue header = 1;</code>
   */
  java.util.List<com.dohko.core.grpc.RpcValue> 
      getHeaderList();
  /**
   * <code>repeated .core.RpcValue header = 1;</code>
   */
  com.dohko.core.grpc.RpcValue getHeader(int index);
  /**
   * <code>repeated .core.RpcValue header = 1;</code>
   */
  int getHeaderCount();
  /**
   * <code>repeated .core.RpcValue header = 1;</code>
   */
  java.util.List<? extends com.dohko.core.grpc.RpcValueOrBuilder> 
      getHeaderOrBuilderList();
  /**
   * <code>repeated .core.RpcValue header = 1;</code>
   */
  com.dohko.core.grpc.RpcValueOrBuilder getHeaderOrBuilder(
      int index);

  /**
   * <code>repeated .core.RpcListValue value = 2;</code>
   */
  java.util.List<com.dohko.core.grpc.RpcListValue> 
      getValueList();
  /**
   * <code>repeated .core.RpcListValue value = 2;</code>
   */
  com.dohko.core.grpc.RpcListValue getValue(int index);
  /**
   * <code>repeated .core.RpcListValue value = 2;</code>
   */
  int getValueCount();
  /**
   * <code>repeated .core.RpcListValue value = 2;</code>
   */
  java.util.List<? extends com.dohko.core.grpc.RpcListValueOrBuilder> 
      getValueOrBuilderList();
  /**
   * <code>repeated .core.RpcListValue value = 2;</code>
   */
  com.dohko.core.grpc.RpcListValueOrBuilder getValueOrBuilder(
      int index);
}
