// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

/**
 * Protobuf type {@code core.RpcDataList}
 */
public  final class RpcDataList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.RpcDataList)
    RpcDataListOrBuilder {
  // Use RpcDataList.newBuilder() to construct.
  private RpcDataList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RpcDataList() {
    header_ = java.util.Collections.emptyList();
    value_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RpcDataList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              header_ = new java.util.ArrayList<com.dohko.core.grpc.RpcValue>();
              mutable_bitField0_ |= 0x00000001;
            }
            header_.add(input.readMessage(com.dohko.core.grpc.RpcValue.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              value_ = new java.util.ArrayList<com.dohko.core.grpc.RpcListValue>();
              mutable_bitField0_ |= 0x00000002;
            }
            value_.add(input.readMessage(com.dohko.core.grpc.RpcListValue.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        header_ = java.util.Collections.unmodifiableList(header_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        value_ = java.util.Collections.unmodifiableList(value_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcDataList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcDataList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dohko.core.grpc.RpcDataList.class, com.dohko.core.grpc.RpcDataList.Builder.class);
  }

  public static final int HEADER_FIELD_NUMBER = 1;
  private java.util.List<com.dohko.core.grpc.RpcValue> header_;
  /**
   * <code>repeated .core.RpcValue header = 1;</code>
   */
  public java.util.List<com.dohko.core.grpc.RpcValue> getHeaderList() {
    return header_;
  }
  /**
   * <code>repeated .core.RpcValue header = 1;</code>
   */
  public java.util.List<? extends com.dohko.core.grpc.RpcValueOrBuilder> 
      getHeaderOrBuilderList() {
    return header_;
  }
  /**
   * <code>repeated .core.RpcValue header = 1;</code>
   */
  public int getHeaderCount() {
    return header_.size();
  }
  /**
   * <code>repeated .core.RpcValue header = 1;</code>
   */
  public com.dohko.core.grpc.RpcValue getHeader(int index) {
    return header_.get(index);
  }
  /**
   * <code>repeated .core.RpcValue header = 1;</code>
   */
  public com.dohko.core.grpc.RpcValueOrBuilder getHeaderOrBuilder(
      int index) {
    return header_.get(index);
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private java.util.List<com.dohko.core.grpc.RpcListValue> value_;
  /**
   * <code>repeated .core.RpcListValue value = 2;</code>
   */
  public java.util.List<com.dohko.core.grpc.RpcListValue> getValueList() {
    return value_;
  }
  /**
   * <code>repeated .core.RpcListValue value = 2;</code>
   */
  public java.util.List<? extends com.dohko.core.grpc.RpcListValueOrBuilder> 
      getValueOrBuilderList() {
    return value_;
  }
  /**
   * <code>repeated .core.RpcListValue value = 2;</code>
   */
  public int getValueCount() {
    return value_.size();
  }
  /**
   * <code>repeated .core.RpcListValue value = 2;</code>
   */
  public com.dohko.core.grpc.RpcListValue getValue(int index) {
    return value_.get(index);
  }
  /**
   * <code>repeated .core.RpcListValue value = 2;</code>
   */
  public com.dohko.core.grpc.RpcListValueOrBuilder getValueOrBuilder(
      int index) {
    return value_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < header_.size(); i++) {
      output.writeMessage(1, header_.get(i));
    }
    for (int i = 0; i < value_.size(); i++) {
      output.writeMessage(2, value_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < header_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, header_.get(i));
    }
    for (int i = 0; i < value_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, value_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.dohko.core.grpc.RpcDataList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dohko.core.grpc.RpcDataList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcDataList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dohko.core.grpc.RpcDataList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcDataList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.dohko.core.grpc.RpcDataList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcDataList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.dohko.core.grpc.RpcDataList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcDataList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.dohko.core.grpc.RpcDataList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dohko.core.grpc.RpcDataList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code core.RpcDataList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.RpcDataList)
      com.dohko.core.grpc.RpcDataListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcDataList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcDataList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dohko.core.grpc.RpcDataList.class, com.dohko.core.grpc.RpcDataList.Builder.class);
    }

    // Construct using com.dohko.core.grpc.RpcDataList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getHeaderFieldBuilder();
        getValueFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        headerBuilder_.clear();
      }
      if (valueBuilder_ == null) {
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        valueBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcDataList_descriptor;
    }

    public com.dohko.core.grpc.RpcDataList getDefaultInstanceForType() {
      return com.dohko.core.grpc.RpcDataList.getDefaultInstance();
    }

    public com.dohko.core.grpc.RpcDataList build() {
      com.dohko.core.grpc.RpcDataList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dohko.core.grpc.RpcDataList buildPartial() {
      com.dohko.core.grpc.RpcDataList result = new com.dohko.core.grpc.RpcDataList(this);
      int from_bitField0_ = bitField0_;
      if (headerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          header_ = java.util.Collections.unmodifiableList(header_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      if (valueBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          value_ = java.util.Collections.unmodifiableList(value_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dohko.core.grpc.RpcDataList) {
        return mergeFrom((com.dohko.core.grpc.RpcDataList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dohko.core.grpc.RpcDataList other) {
      if (other == com.dohko.core.grpc.RpcDataList.getDefaultInstance()) return this;
      if (headerBuilder_ == null) {
        if (!other.header_.isEmpty()) {
          if (header_.isEmpty()) {
            header_ = other.header_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHeaderIsMutable();
            header_.addAll(other.header_);
          }
          onChanged();
        }
      } else {
        if (!other.header_.isEmpty()) {
          if (headerBuilder_.isEmpty()) {
            headerBuilder_.dispose();
            headerBuilder_ = null;
            header_ = other.header_;
            bitField0_ = (bitField0_ & ~0x00000001);
            headerBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getHeaderFieldBuilder() : null;
          } else {
            headerBuilder_.addAllMessages(other.header_);
          }
        }
      }
      if (valueBuilder_ == null) {
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
      } else {
        if (!other.value_.isEmpty()) {
          if (valueBuilder_.isEmpty()) {
            valueBuilder_.dispose();
            valueBuilder_ = null;
            value_ = other.value_;
            bitField0_ = (bitField0_ & ~0x00000002);
            valueBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getValueFieldBuilder() : null;
          } else {
            valueBuilder_.addAllMessages(other.value_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dohko.core.grpc.RpcDataList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dohko.core.grpc.RpcDataList) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.dohko.core.grpc.RpcValue> header_ =
      java.util.Collections.emptyList();
    private void ensureHeaderIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        header_ = new java.util.ArrayList<com.dohko.core.grpc.RpcValue>(header_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.dohko.core.grpc.RpcValue, com.dohko.core.grpc.RpcValue.Builder, com.dohko.core.grpc.RpcValueOrBuilder> headerBuilder_;

    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public java.util.List<com.dohko.core.grpc.RpcValue> getHeaderList() {
      if (headerBuilder_ == null) {
        return java.util.Collections.unmodifiableList(header_);
      } else {
        return headerBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public int getHeaderCount() {
      if (headerBuilder_ == null) {
        return header_.size();
      } else {
        return headerBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public com.dohko.core.grpc.RpcValue getHeader(int index) {
      if (headerBuilder_ == null) {
        return header_.get(index);
      } else {
        return headerBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public Builder setHeader(
        int index, com.dohko.core.grpc.RpcValue value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.set(index, value);
        onChanged();
      } else {
        headerBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public Builder setHeader(
        int index, com.dohko.core.grpc.RpcValue.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.set(index, builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public Builder addHeader(com.dohko.core.grpc.RpcValue value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.add(value);
        onChanged();
      } else {
        headerBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public Builder addHeader(
        int index, com.dohko.core.grpc.RpcValue value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.add(index, value);
        onChanged();
      } else {
        headerBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public Builder addHeader(
        com.dohko.core.grpc.RpcValue.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.add(builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public Builder addHeader(
        int index, com.dohko.core.grpc.RpcValue.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.add(index, builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public Builder addAllHeader(
        java.lang.Iterable<? extends com.dohko.core.grpc.RpcValue> values) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, header_);
        onChanged();
      } else {
        headerBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        headerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public Builder removeHeader(int index) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.remove(index);
        onChanged();
      } else {
        headerBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public com.dohko.core.grpc.RpcValue.Builder getHeaderBuilder(
        int index) {
      return getHeaderFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public com.dohko.core.grpc.RpcValueOrBuilder getHeaderOrBuilder(
        int index) {
      if (headerBuilder_ == null) {
        return header_.get(index);  } else {
        return headerBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public java.util.List<? extends com.dohko.core.grpc.RpcValueOrBuilder> 
         getHeaderOrBuilderList() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(header_);
      }
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public com.dohko.core.grpc.RpcValue.Builder addHeaderBuilder() {
      return getHeaderFieldBuilder().addBuilder(
          com.dohko.core.grpc.RpcValue.getDefaultInstance());
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public com.dohko.core.grpc.RpcValue.Builder addHeaderBuilder(
        int index) {
      return getHeaderFieldBuilder().addBuilder(
          index, com.dohko.core.grpc.RpcValue.getDefaultInstance());
    }
    /**
     * <code>repeated .core.RpcValue header = 1;</code>
     */
    public java.util.List<com.dohko.core.grpc.RpcValue.Builder> 
         getHeaderBuilderList() {
      return getHeaderFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.dohko.core.grpc.RpcValue, com.dohko.core.grpc.RpcValue.Builder, com.dohko.core.grpc.RpcValueOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.dohko.core.grpc.RpcValue, com.dohko.core.grpc.RpcValue.Builder, com.dohko.core.grpc.RpcValueOrBuilder>(
                header_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.util.List<com.dohko.core.grpc.RpcListValue> value_ =
      java.util.Collections.emptyList();
    private void ensureValueIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        value_ = new java.util.ArrayList<com.dohko.core.grpc.RpcListValue>(value_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.dohko.core.grpc.RpcListValue, com.dohko.core.grpc.RpcListValue.Builder, com.dohko.core.grpc.RpcListValueOrBuilder> valueBuilder_;

    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public java.util.List<com.dohko.core.grpc.RpcListValue> getValueList() {
      if (valueBuilder_ == null) {
        return java.util.Collections.unmodifiableList(value_);
      } else {
        return valueBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public int getValueCount() {
      if (valueBuilder_ == null) {
        return value_.size();
      } else {
        return valueBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public com.dohko.core.grpc.RpcListValue getValue(int index) {
      if (valueBuilder_ == null) {
        return value_.get(index);
      } else {
        return valueBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public Builder setValue(
        int index, com.dohko.core.grpc.RpcListValue value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValueIsMutable();
        value_.set(index, value);
        onChanged();
      } else {
        valueBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public Builder setValue(
        int index, com.dohko.core.grpc.RpcListValue.Builder builderForValue) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.set(index, builderForValue.build());
        onChanged();
      } else {
        valueBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public Builder addValue(com.dohko.core.grpc.RpcListValue value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValueIsMutable();
        value_.add(value);
        onChanged();
      } else {
        valueBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public Builder addValue(
        int index, com.dohko.core.grpc.RpcListValue value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValueIsMutable();
        value_.add(index, value);
        onChanged();
      } else {
        valueBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public Builder addValue(
        com.dohko.core.grpc.RpcListValue.Builder builderForValue) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.add(builderForValue.build());
        onChanged();
      } else {
        valueBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public Builder addValue(
        int index, com.dohko.core.grpc.RpcListValue.Builder builderForValue) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.add(index, builderForValue.build());
        onChanged();
      } else {
        valueBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public Builder addAllValue(
        java.lang.Iterable<? extends com.dohko.core.grpc.RpcListValue> values) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, value_);
        onChanged();
      } else {
        valueBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        valueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public Builder removeValue(int index) {
      if (valueBuilder_ == null) {
        ensureValueIsMutable();
        value_.remove(index);
        onChanged();
      } else {
        valueBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public com.dohko.core.grpc.RpcListValue.Builder getValueBuilder(
        int index) {
      return getValueFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public com.dohko.core.grpc.RpcListValueOrBuilder getValueOrBuilder(
        int index) {
      if (valueBuilder_ == null) {
        return value_.get(index);  } else {
        return valueBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public java.util.List<? extends com.dohko.core.grpc.RpcListValueOrBuilder> 
         getValueOrBuilderList() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(value_);
      }
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public com.dohko.core.grpc.RpcListValue.Builder addValueBuilder() {
      return getValueFieldBuilder().addBuilder(
          com.dohko.core.grpc.RpcListValue.getDefaultInstance());
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public com.dohko.core.grpc.RpcListValue.Builder addValueBuilder(
        int index) {
      return getValueFieldBuilder().addBuilder(
          index, com.dohko.core.grpc.RpcListValue.getDefaultInstance());
    }
    /**
     * <code>repeated .core.RpcListValue value = 2;</code>
     */
    public java.util.List<com.dohko.core.grpc.RpcListValue.Builder> 
         getValueBuilderList() {
      return getValueFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.dohko.core.grpc.RpcListValue, com.dohko.core.grpc.RpcListValue.Builder, com.dohko.core.grpc.RpcListValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.dohko.core.grpc.RpcListValue, com.dohko.core.grpc.RpcListValue.Builder, com.dohko.core.grpc.RpcListValueOrBuilder>(
                value_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:core.RpcDataList)
  }

  // @@protoc_insertion_point(class_scope:core.RpcDataList)
  private static final com.dohko.core.grpc.RpcDataList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dohko.core.grpc.RpcDataList();
  }

  public static com.dohko.core.grpc.RpcDataList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcDataList>
      PARSER = new com.google.protobuf.AbstractParser<RpcDataList>() {
    public RpcDataList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new RpcDataList(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<RpcDataList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcDataList> getParserForType() {
    return PARSER;
  }

  public com.dohko.core.grpc.RpcDataList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

