// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

public interface RpcHolderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.RpcHolder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .core.RpcDataMap dataMap = 1;</code>
   */
  boolean hasDataMap();
  /**
   * <code>optional .core.RpcDataMap dataMap = 1;</code>
   */
  com.dohko.core.grpc.RpcDataMap getDataMap();
  /**
   * <code>optional .core.RpcDataMap dataMap = 1;</code>
   */
  com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder();
}
