// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

/**
 * Protobuf type {@code core.RpcHolder}
 */
public  final class RpcHolder extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.RpcHolder)
    RpcHolderOrBuilder {
  // Use RpcHolder.newBuilder() to construct.
  private RpcHolder(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RpcHolder() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RpcHolder(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.dohko.core.grpc.RpcDataMap.Builder subBuilder = null;
            if (dataMap_ != null) {
              subBuilder = dataMap_.toBuilder();
            }
            dataMap_ = input.readMessage(com.dohko.core.grpc.RpcDataMap.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dataMap_);
              dataMap_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcHolder_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcHolder_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dohko.core.grpc.RpcHolder.class, com.dohko.core.grpc.RpcHolder.Builder.class);
  }

  public static final int DATAMAP_FIELD_NUMBER = 1;
  private com.dohko.core.grpc.RpcDataMap dataMap_;
  /**
   * <code>optional .core.RpcDataMap dataMap = 1;</code>
   */
  public boolean hasDataMap() {
    return dataMap_ != null;
  }
  /**
   * <code>optional .core.RpcDataMap dataMap = 1;</code>
   */
  public com.dohko.core.grpc.RpcDataMap getDataMap() {
    return dataMap_ == null ? com.dohko.core.grpc.RpcDataMap.getDefaultInstance() : dataMap_;
  }
  /**
   * <code>optional .core.RpcDataMap dataMap = 1;</code>
   */
  public com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder() {
    return getDataMap();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataMap_ != null) {
      output.writeMessage(1, getDataMap());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataMap_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDataMap());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.dohko.core.grpc.RpcHolder parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dohko.core.grpc.RpcHolder parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcHolder parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dohko.core.grpc.RpcHolder parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcHolder parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.dohko.core.grpc.RpcHolder parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcHolder parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.dohko.core.grpc.RpcHolder parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcHolder parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.dohko.core.grpc.RpcHolder parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dohko.core.grpc.RpcHolder prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code core.RpcHolder}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.RpcHolder)
      com.dohko.core.grpc.RpcHolderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcHolder_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcHolder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dohko.core.grpc.RpcHolder.class, com.dohko.core.grpc.RpcHolder.Builder.class);
    }

    // Construct using com.dohko.core.grpc.RpcHolder.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (dataMapBuilder_ == null) {
        dataMap_ = null;
      } else {
        dataMap_ = null;
        dataMapBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcHolder_descriptor;
    }

    public com.dohko.core.grpc.RpcHolder getDefaultInstanceForType() {
      return com.dohko.core.grpc.RpcHolder.getDefaultInstance();
    }

    public com.dohko.core.grpc.RpcHolder build() {
      com.dohko.core.grpc.RpcHolder result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dohko.core.grpc.RpcHolder buildPartial() {
      com.dohko.core.grpc.RpcHolder result = new com.dohko.core.grpc.RpcHolder(this);
      if (dataMapBuilder_ == null) {
        result.dataMap_ = dataMap_;
      } else {
        result.dataMap_ = dataMapBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dohko.core.grpc.RpcHolder) {
        return mergeFrom((com.dohko.core.grpc.RpcHolder)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dohko.core.grpc.RpcHolder other) {
      if (other == com.dohko.core.grpc.RpcHolder.getDefaultInstance()) return this;
      if (other.hasDataMap()) {
        mergeDataMap(other.getDataMap());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dohko.core.grpc.RpcHolder parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dohko.core.grpc.RpcHolder) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.dohko.core.grpc.RpcDataMap dataMap_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder> dataMapBuilder_;
    /**
     * <code>optional .core.RpcDataMap dataMap = 1;</code>
     */
    public boolean hasDataMap() {
      return dataMapBuilder_ != null || dataMap_ != null;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 1;</code>
     */
    public com.dohko.core.grpc.RpcDataMap getDataMap() {
      if (dataMapBuilder_ == null) {
        return dataMap_ == null ? com.dohko.core.grpc.RpcDataMap.getDefaultInstance() : dataMap_;
      } else {
        return dataMapBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 1;</code>
     */
    public Builder setDataMap(com.dohko.core.grpc.RpcDataMap value) {
      if (dataMapBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataMap_ = value;
        onChanged();
      } else {
        dataMapBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 1;</code>
     */
    public Builder setDataMap(
        com.dohko.core.grpc.RpcDataMap.Builder builderForValue) {
      if (dataMapBuilder_ == null) {
        dataMap_ = builderForValue.build();
        onChanged();
      } else {
        dataMapBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 1;</code>
     */
    public Builder mergeDataMap(com.dohko.core.grpc.RpcDataMap value) {
      if (dataMapBuilder_ == null) {
        if (dataMap_ != null) {
          dataMap_ =
            com.dohko.core.grpc.RpcDataMap.newBuilder(dataMap_).mergeFrom(value).buildPartial();
        } else {
          dataMap_ = value;
        }
        onChanged();
      } else {
        dataMapBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 1;</code>
     */
    public Builder clearDataMap() {
      if (dataMapBuilder_ == null) {
        dataMap_ = null;
        onChanged();
      } else {
        dataMap_ = null;
        dataMapBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 1;</code>
     */
    public com.dohko.core.grpc.RpcDataMap.Builder getDataMapBuilder() {
      
      onChanged();
      return getDataMapFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 1;</code>
     */
    public com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder() {
      if (dataMapBuilder_ != null) {
        return dataMapBuilder_.getMessageOrBuilder();
      } else {
        return dataMap_ == null ?
            com.dohko.core.grpc.RpcDataMap.getDefaultInstance() : dataMap_;
      }
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder> 
        getDataMapFieldBuilder() {
      if (dataMapBuilder_ == null) {
        dataMapBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder>(
                getDataMap(),
                getParentForChildren(),
                isClean());
        dataMap_ = null;
      }
      return dataMapBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:core.RpcHolder)
  }

  // @@protoc_insertion_point(class_scope:core.RpcHolder)
  private static final com.dohko.core.grpc.RpcHolder DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dohko.core.grpc.RpcHolder();
  }

  public static com.dohko.core.grpc.RpcHolder getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcHolder>
      PARSER = new com.google.protobuf.AbstractParser<RpcHolder>() {
    public RpcHolder parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new RpcHolder(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<RpcHolder> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcHolder> getParserForType() {
    return PARSER;
  }

  public com.dohko.core.grpc.RpcHolder getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

