// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

public interface RpcListValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.RpcListValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .core.RpcValue value = 1;</code>
   */
  java.util.List<com.dohko.core.grpc.RpcValue> 
      getValueList();
  /**
   * <code>repeated .core.RpcValue value = 1;</code>
   */
  com.dohko.core.grpc.RpcValue getValue(int index);
  /**
   * <code>repeated .core.RpcValue value = 1;</code>
   */
  int getValueCount();
  /**
   * <code>repeated .core.RpcValue value = 1;</code>
   */
  java.util.List<? extends com.dohko.core.grpc.RpcValueOrBuilder> 
      getValueOrBuilderList();
  /**
   * <code>repeated .core.RpcValue value = 1;</code>
   */
  com.dohko.core.grpc.RpcValueOrBuilder getValueOrBuilder(
      int index);
}
