// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

/**
 * Protobuf type {@code core.RpcResponse}
 */
public  final class RpcResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.RpcResponse)
    RpcResponseOrBuilder {
  // Use RpcResponse.newBuilder() to construct.
  private RpcResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RpcResponse() {
    success_ = false;
    returnCode_ = "";
    returnMsg_ = "";
    traceID_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RpcResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            success_ = input.readBool();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            returnCode_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            returnMsg_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            traceID_ = s;
            break;
          }
          case 42: {
            com.dohko.core.grpc.RpcDataMap.Builder subBuilder = null;
            if (dataMap_ != null) {
              subBuilder = dataMap_.toBuilder();
            }
            dataMap_ = input.readMessage(com.dohko.core.grpc.RpcDataMap.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dataMap_);
              dataMap_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dohko.core.grpc.RpcResponse.class, com.dohko.core.grpc.RpcResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <code>optional bool success = 1;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  public static final int RETURNCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object returnCode_;
  /**
   * <code>optional string returnCode = 2;</code>
   */
  public java.lang.String getReturnCode() {
    java.lang.Object ref = returnCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      returnCode_ = s;
      return s;
    }
  }
  /**
   * <code>optional string returnCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getReturnCodeBytes() {
    java.lang.Object ref = returnCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      returnCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETURNMSG_FIELD_NUMBER = 3;
  private volatile java.lang.Object returnMsg_;
  /**
   * <code>optional string returnMsg = 3;</code>
   */
  public java.lang.String getReturnMsg() {
    java.lang.Object ref = returnMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      returnMsg_ = s;
      return s;
    }
  }
  /**
   * <code>optional string returnMsg = 3;</code>
   */
  public com.google.protobuf.ByteString
      getReturnMsgBytes() {
    java.lang.Object ref = returnMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      returnMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACEID_FIELD_NUMBER = 4;
  private volatile java.lang.Object traceID_;
  /**
   * <code>optional string traceID = 4;</code>
   */
  public java.lang.String getTraceID() {
    java.lang.Object ref = traceID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string traceID = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTraceIDBytes() {
    java.lang.Object ref = traceID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATAMAP_FIELD_NUMBER = 5;
  private com.dohko.core.grpc.RpcDataMap dataMap_;
  /**
   * <code>optional .core.RpcDataMap dataMap = 5;</code>
   */
  public boolean hasDataMap() {
    return dataMap_ != null;
  }
  /**
   * <code>optional .core.RpcDataMap dataMap = 5;</code>
   */
  public com.dohko.core.grpc.RpcDataMap getDataMap() {
    return dataMap_ == null ? com.dohko.core.grpc.RpcDataMap.getDefaultInstance() : dataMap_;
  }
  /**
   * <code>optional .core.RpcDataMap dataMap = 5;</code>
   */
  public com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder() {
    return getDataMap();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (!getReturnCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, returnCode_);
    }
    if (!getReturnMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, returnMsg_);
    }
    if (!getTraceIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, traceID_);
    }
    if (dataMap_ != null) {
      output.writeMessage(5, getDataMap());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (!getReturnCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, returnCode_);
    }
    if (!getReturnMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, returnMsg_);
    }
    if (!getTraceIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, traceID_);
    }
    if (dataMap_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDataMap());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.dohko.core.grpc.RpcResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dohko.core.grpc.RpcResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dohko.core.grpc.RpcResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.dohko.core.grpc.RpcResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.dohko.core.grpc.RpcResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.dohko.core.grpc.RpcResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dohko.core.grpc.RpcResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code core.RpcResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.RpcResponse)
      com.dohko.core.grpc.RpcResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dohko.core.grpc.RpcResponse.class, com.dohko.core.grpc.RpcResponse.Builder.class);
    }

    // Construct using com.dohko.core.grpc.RpcResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      success_ = false;

      returnCode_ = "";

      returnMsg_ = "";

      traceID_ = "";

      if (dataMapBuilder_ == null) {
        dataMap_ = null;
      } else {
        dataMap_ = null;
        dataMapBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcResponse_descriptor;
    }

    public com.dohko.core.grpc.RpcResponse getDefaultInstanceForType() {
      return com.dohko.core.grpc.RpcResponse.getDefaultInstance();
    }

    public com.dohko.core.grpc.RpcResponse build() {
      com.dohko.core.grpc.RpcResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dohko.core.grpc.RpcResponse buildPartial() {
      com.dohko.core.grpc.RpcResponse result = new com.dohko.core.grpc.RpcResponse(this);
      result.success_ = success_;
      result.returnCode_ = returnCode_;
      result.returnMsg_ = returnMsg_;
      result.traceID_ = traceID_;
      if (dataMapBuilder_ == null) {
        result.dataMap_ = dataMap_;
      } else {
        result.dataMap_ = dataMapBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dohko.core.grpc.RpcResponse) {
        return mergeFrom((com.dohko.core.grpc.RpcResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dohko.core.grpc.RpcResponse other) {
      if (other == com.dohko.core.grpc.RpcResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (!other.getReturnCode().isEmpty()) {
        returnCode_ = other.returnCode_;
        onChanged();
      }
      if (!other.getReturnMsg().isEmpty()) {
        returnMsg_ = other.returnMsg_;
        onChanged();
      }
      if (!other.getTraceID().isEmpty()) {
        traceID_ = other.traceID_;
        onChanged();
      }
      if (other.hasDataMap()) {
        mergeDataMap(other.getDataMap());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dohko.core.grpc.RpcResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dohko.core.grpc.RpcResponse) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean success_ ;
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>optional bool success = 1;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool success = 1;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object returnCode_ = "";
    /**
     * <code>optional string returnCode = 2;</code>
     */
    public java.lang.String getReturnCode() {
      java.lang.Object ref = returnCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        returnCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string returnCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReturnCodeBytes() {
      java.lang.Object ref = returnCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string returnCode = 2;</code>
     */
    public Builder setReturnCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      returnCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string returnCode = 2;</code>
     */
    public Builder clearReturnCode() {
      
      returnCode_ = getDefaultInstance().getReturnCode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string returnCode = 2;</code>
     */
    public Builder setReturnCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      returnCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object returnMsg_ = "";
    /**
     * <code>optional string returnMsg = 3;</code>
     */
    public java.lang.String getReturnMsg() {
      java.lang.Object ref = returnMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        returnMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string returnMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReturnMsgBytes() {
      java.lang.Object ref = returnMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string returnMsg = 3;</code>
     */
    public Builder setReturnMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      returnMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string returnMsg = 3;</code>
     */
    public Builder clearReturnMsg() {
      
      returnMsg_ = getDefaultInstance().getReturnMsg();
      onChanged();
      return this;
    }
    /**
     * <code>optional string returnMsg = 3;</code>
     */
    public Builder setReturnMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      returnMsg_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object traceID_ = "";
    /**
     * <code>optional string traceID = 4;</code>
     */
    public java.lang.String getTraceID() {
      java.lang.Object ref = traceID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string traceID = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTraceIDBytes() {
      java.lang.Object ref = traceID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string traceID = 4;</code>
     */
    public Builder setTraceID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      traceID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceID = 4;</code>
     */
    public Builder clearTraceID() {
      
      traceID_ = getDefaultInstance().getTraceID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceID = 4;</code>
     */
    public Builder setTraceIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      traceID_ = value;
      onChanged();
      return this;
    }

    private com.dohko.core.grpc.RpcDataMap dataMap_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder> dataMapBuilder_;
    /**
     * <code>optional .core.RpcDataMap dataMap = 5;</code>
     */
    public boolean hasDataMap() {
      return dataMapBuilder_ != null || dataMap_ != null;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 5;</code>
     */
    public com.dohko.core.grpc.RpcDataMap getDataMap() {
      if (dataMapBuilder_ == null) {
        return dataMap_ == null ? com.dohko.core.grpc.RpcDataMap.getDefaultInstance() : dataMap_;
      } else {
        return dataMapBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 5;</code>
     */
    public Builder setDataMap(com.dohko.core.grpc.RpcDataMap value) {
      if (dataMapBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataMap_ = value;
        onChanged();
      } else {
        dataMapBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 5;</code>
     */
    public Builder setDataMap(
        com.dohko.core.grpc.RpcDataMap.Builder builderForValue) {
      if (dataMapBuilder_ == null) {
        dataMap_ = builderForValue.build();
        onChanged();
      } else {
        dataMapBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 5;</code>
     */
    public Builder mergeDataMap(com.dohko.core.grpc.RpcDataMap value) {
      if (dataMapBuilder_ == null) {
        if (dataMap_ != null) {
          dataMap_ =
            com.dohko.core.grpc.RpcDataMap.newBuilder(dataMap_).mergeFrom(value).buildPartial();
        } else {
          dataMap_ = value;
        }
        onChanged();
      } else {
        dataMapBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 5;</code>
     */
    public Builder clearDataMap() {
      if (dataMapBuilder_ == null) {
        dataMap_ = null;
        onChanged();
      } else {
        dataMap_ = null;
        dataMapBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 5;</code>
     */
    public com.dohko.core.grpc.RpcDataMap.Builder getDataMapBuilder() {
      
      onChanged();
      return getDataMapFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 5;</code>
     */
    public com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder() {
      if (dataMapBuilder_ != null) {
        return dataMapBuilder_.getMessageOrBuilder();
      } else {
        return dataMap_ == null ?
            com.dohko.core.grpc.RpcDataMap.getDefaultInstance() : dataMap_;
      }
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder> 
        getDataMapFieldBuilder() {
      if (dataMapBuilder_ == null) {
        dataMapBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder>(
                getDataMap(),
                getParentForChildren(),
                isClean());
        dataMap_ = null;
      }
      return dataMapBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:core.RpcResponse)
  }

  // @@protoc_insertion_point(class_scope:core.RpcResponse)
  private static final com.dohko.core.grpc.RpcResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dohko.core.grpc.RpcResponse();
  }

  public static com.dohko.core.grpc.RpcResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcResponse>
      PARSER = new com.google.protobuf.AbstractParser<RpcResponse>() {
    public RpcResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new RpcResponse(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<RpcResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcResponse> getParserForType() {
    return PARSER;
  }

  public com.dohko.core.grpc.RpcResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

