// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

/**
 * Protobuf type {@code core.RpcRequest}
 */
public  final class RpcRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.RpcRequest)
    RpcRequestOrBuilder {
  // Use RpcRequest.newBuilder() to construct.
  private RpcRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RpcRequest() {
    service_ = "";
    traceID_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RpcRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            service_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            traceID_ = s;
            break;
          }
          case 26: {
            com.dohko.core.grpc.RpcDataMap.Builder subBuilder = null;
            if (dataMap_ != null) {
              subBuilder = dataMap_.toBuilder();
            }
            dataMap_ = input.readMessage(com.dohko.core.grpc.RpcDataMap.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dataMap_);
              dataMap_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.dohko.core.grpc.RpcHolder.Builder subBuilder = null;
            if (holder_ != null) {
              subBuilder = holder_.toBuilder();
            }
            holder_ = input.readMessage(com.dohko.core.grpc.RpcHolder.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(holder_);
              holder_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dohko.core.grpc.RpcRequest.class, com.dohko.core.grpc.RpcRequest.Builder.class);
  }

  public static final int SERVICE_FIELD_NUMBER = 1;
  private volatile java.lang.Object service_;
  /**
   * <code>optional string service = 1;</code>
   */
  public java.lang.String getService() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      service_ = s;
      return s;
    }
  }
  /**
   * <code>optional string service = 1;</code>
   */
  public com.google.protobuf.ByteString
      getServiceBytes() {
    java.lang.Object ref = service_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      service_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRACEID_FIELD_NUMBER = 2;
  private volatile java.lang.Object traceID_;
  /**
   * <code>optional string traceID = 2;</code>
   */
  public java.lang.String getTraceID() {
    java.lang.Object ref = traceID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceID_ = s;
      return s;
    }
  }
  /**
   * <code>optional string traceID = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTraceIDBytes() {
    java.lang.Object ref = traceID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATAMAP_FIELD_NUMBER = 3;
  private com.dohko.core.grpc.RpcDataMap dataMap_;
  /**
   * <code>optional .core.RpcDataMap dataMap = 3;</code>
   */
  public boolean hasDataMap() {
    return dataMap_ != null;
  }
  /**
   * <code>optional .core.RpcDataMap dataMap = 3;</code>
   */
  public com.dohko.core.grpc.RpcDataMap getDataMap() {
    return dataMap_ == null ? com.dohko.core.grpc.RpcDataMap.getDefaultInstance() : dataMap_;
  }
  /**
   * <code>optional .core.RpcDataMap dataMap = 3;</code>
   */
  public com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder() {
    return getDataMap();
  }

  public static final int HOLDER_FIELD_NUMBER = 4;
  private com.dohko.core.grpc.RpcHolder holder_;
  /**
   * <code>optional .core.RpcHolder holder = 4;</code>
   */
  public boolean hasHolder() {
    return holder_ != null;
  }
  /**
   * <code>optional .core.RpcHolder holder = 4;</code>
   */
  public com.dohko.core.grpc.RpcHolder getHolder() {
    return holder_ == null ? com.dohko.core.grpc.RpcHolder.getDefaultInstance() : holder_;
  }
  /**
   * <code>optional .core.RpcHolder holder = 4;</code>
   */
  public com.dohko.core.grpc.RpcHolderOrBuilder getHolderOrBuilder() {
    return getHolder();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getServiceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, service_);
    }
    if (!getTraceIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, traceID_);
    }
    if (dataMap_ != null) {
      output.writeMessage(3, getDataMap());
    }
    if (holder_ != null) {
      output.writeMessage(4, getHolder());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServiceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, service_);
    }
    if (!getTraceIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, traceID_);
    }
    if (dataMap_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDataMap());
    }
    if (holder_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getHolder());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.dohko.core.grpc.RpcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dohko.core.grpc.RpcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dohko.core.grpc.RpcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.dohko.core.grpc.RpcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.dohko.core.grpc.RpcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.dohko.core.grpc.RpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dohko.core.grpc.RpcRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code core.RpcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.RpcRequest)
      com.dohko.core.grpc.RpcRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dohko.core.grpc.RpcRequest.class, com.dohko.core.grpc.RpcRequest.Builder.class);
    }

    // Construct using com.dohko.core.grpc.RpcRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      service_ = "";

      traceID_ = "";

      if (dataMapBuilder_ == null) {
        dataMap_ = null;
      } else {
        dataMap_ = null;
        dataMapBuilder_ = null;
      }
      if (holderBuilder_ == null) {
        holder_ = null;
      } else {
        holder_ = null;
        holderBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcRequest_descriptor;
    }

    public com.dohko.core.grpc.RpcRequest getDefaultInstanceForType() {
      return com.dohko.core.grpc.RpcRequest.getDefaultInstance();
    }

    public com.dohko.core.grpc.RpcRequest build() {
      com.dohko.core.grpc.RpcRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dohko.core.grpc.RpcRequest buildPartial() {
      com.dohko.core.grpc.RpcRequest result = new com.dohko.core.grpc.RpcRequest(this);
      result.service_ = service_;
      result.traceID_ = traceID_;
      if (dataMapBuilder_ == null) {
        result.dataMap_ = dataMap_;
      } else {
        result.dataMap_ = dataMapBuilder_.build();
      }
      if (holderBuilder_ == null) {
        result.holder_ = holder_;
      } else {
        result.holder_ = holderBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dohko.core.grpc.RpcRequest) {
        return mergeFrom((com.dohko.core.grpc.RpcRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dohko.core.grpc.RpcRequest other) {
      if (other == com.dohko.core.grpc.RpcRequest.getDefaultInstance()) return this;
      if (!other.getService().isEmpty()) {
        service_ = other.service_;
        onChanged();
      }
      if (!other.getTraceID().isEmpty()) {
        traceID_ = other.traceID_;
        onChanged();
      }
      if (other.hasDataMap()) {
        mergeDataMap(other.getDataMap());
      }
      if (other.hasHolder()) {
        mergeHolder(other.getHolder());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dohko.core.grpc.RpcRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dohko.core.grpc.RpcRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object service_ = "";
    /**
     * <code>optional string service = 1;</code>
     */
    public java.lang.String getService() {
      java.lang.Object ref = service_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        service_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string service = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      java.lang.Object ref = service_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string service = 1;</code>
     */
    public Builder setService(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      service_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string service = 1;</code>
     */
    public Builder clearService() {
      
      service_ = getDefaultInstance().getService();
      onChanged();
      return this;
    }
    /**
     * <code>optional string service = 1;</code>
     */
    public Builder setServiceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      service_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object traceID_ = "";
    /**
     * <code>optional string traceID = 2;</code>
     */
    public java.lang.String getTraceID() {
      java.lang.Object ref = traceID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string traceID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTraceIDBytes() {
      java.lang.Object ref = traceID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string traceID = 2;</code>
     */
    public Builder setTraceID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      traceID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceID = 2;</code>
     */
    public Builder clearTraceID() {
      
      traceID_ = getDefaultInstance().getTraceID();
      onChanged();
      return this;
    }
    /**
     * <code>optional string traceID = 2;</code>
     */
    public Builder setTraceIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      traceID_ = value;
      onChanged();
      return this;
    }

    private com.dohko.core.grpc.RpcDataMap dataMap_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder> dataMapBuilder_;
    /**
     * <code>optional .core.RpcDataMap dataMap = 3;</code>
     */
    public boolean hasDataMap() {
      return dataMapBuilder_ != null || dataMap_ != null;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 3;</code>
     */
    public com.dohko.core.grpc.RpcDataMap getDataMap() {
      if (dataMapBuilder_ == null) {
        return dataMap_ == null ? com.dohko.core.grpc.RpcDataMap.getDefaultInstance() : dataMap_;
      } else {
        return dataMapBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 3;</code>
     */
    public Builder setDataMap(com.dohko.core.grpc.RpcDataMap value) {
      if (dataMapBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataMap_ = value;
        onChanged();
      } else {
        dataMapBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 3;</code>
     */
    public Builder setDataMap(
        com.dohko.core.grpc.RpcDataMap.Builder builderForValue) {
      if (dataMapBuilder_ == null) {
        dataMap_ = builderForValue.build();
        onChanged();
      } else {
        dataMapBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 3;</code>
     */
    public Builder mergeDataMap(com.dohko.core.grpc.RpcDataMap value) {
      if (dataMapBuilder_ == null) {
        if (dataMap_ != null) {
          dataMap_ =
            com.dohko.core.grpc.RpcDataMap.newBuilder(dataMap_).mergeFrom(value).buildPartial();
        } else {
          dataMap_ = value;
        }
        onChanged();
      } else {
        dataMapBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 3;</code>
     */
    public Builder clearDataMap() {
      if (dataMapBuilder_ == null) {
        dataMap_ = null;
        onChanged();
      } else {
        dataMap_ = null;
        dataMapBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 3;</code>
     */
    public com.dohko.core.grpc.RpcDataMap.Builder getDataMapBuilder() {
      
      onChanged();
      return getDataMapFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 3;</code>
     */
    public com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder() {
      if (dataMapBuilder_ != null) {
        return dataMapBuilder_.getMessageOrBuilder();
      } else {
        return dataMap_ == null ?
            com.dohko.core.grpc.RpcDataMap.getDefaultInstance() : dataMap_;
      }
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder> 
        getDataMapFieldBuilder() {
      if (dataMapBuilder_ == null) {
        dataMapBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder>(
                getDataMap(),
                getParentForChildren(),
                isClean());
        dataMap_ = null;
      }
      return dataMapBuilder_;
    }

    private com.dohko.core.grpc.RpcHolder holder_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcHolder, com.dohko.core.grpc.RpcHolder.Builder, com.dohko.core.grpc.RpcHolderOrBuilder> holderBuilder_;
    /**
     * <code>optional .core.RpcHolder holder = 4;</code>
     */
    public boolean hasHolder() {
      return holderBuilder_ != null || holder_ != null;
    }
    /**
     * <code>optional .core.RpcHolder holder = 4;</code>
     */
    public com.dohko.core.grpc.RpcHolder getHolder() {
      if (holderBuilder_ == null) {
        return holder_ == null ? com.dohko.core.grpc.RpcHolder.getDefaultInstance() : holder_;
      } else {
        return holderBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .core.RpcHolder holder = 4;</code>
     */
    public Builder setHolder(com.dohko.core.grpc.RpcHolder value) {
      if (holderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        holder_ = value;
        onChanged();
      } else {
        holderBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .core.RpcHolder holder = 4;</code>
     */
    public Builder setHolder(
        com.dohko.core.grpc.RpcHolder.Builder builderForValue) {
      if (holderBuilder_ == null) {
        holder_ = builderForValue.build();
        onChanged();
      } else {
        holderBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .core.RpcHolder holder = 4;</code>
     */
    public Builder mergeHolder(com.dohko.core.grpc.RpcHolder value) {
      if (holderBuilder_ == null) {
        if (holder_ != null) {
          holder_ =
            com.dohko.core.grpc.RpcHolder.newBuilder(holder_).mergeFrom(value).buildPartial();
        } else {
          holder_ = value;
        }
        onChanged();
      } else {
        holderBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .core.RpcHolder holder = 4;</code>
     */
    public Builder clearHolder() {
      if (holderBuilder_ == null) {
        holder_ = null;
        onChanged();
      } else {
        holder_ = null;
        holderBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .core.RpcHolder holder = 4;</code>
     */
    public com.dohko.core.grpc.RpcHolder.Builder getHolderBuilder() {
      
      onChanged();
      return getHolderFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .core.RpcHolder holder = 4;</code>
     */
    public com.dohko.core.grpc.RpcHolderOrBuilder getHolderOrBuilder() {
      if (holderBuilder_ != null) {
        return holderBuilder_.getMessageOrBuilder();
      } else {
        return holder_ == null ?
            com.dohko.core.grpc.RpcHolder.getDefaultInstance() : holder_;
      }
    }
    /**
     * <code>optional .core.RpcHolder holder = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcHolder, com.dohko.core.grpc.RpcHolder.Builder, com.dohko.core.grpc.RpcHolderOrBuilder> 
        getHolderFieldBuilder() {
      if (holderBuilder_ == null) {
        holderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.dohko.core.grpc.RpcHolder, com.dohko.core.grpc.RpcHolder.Builder, com.dohko.core.grpc.RpcHolderOrBuilder>(
                getHolder(),
                getParentForChildren(),
                isClean());
        holder_ = null;
      }
      return holderBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:core.RpcRequest)
  }

  // @@protoc_insertion_point(class_scope:core.RpcRequest)
  private static final com.dohko.core.grpc.RpcRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dohko.core.grpc.RpcRequest();
  }

  public static com.dohko.core.grpc.RpcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcRequest>
      PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
    public RpcRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new RpcRequest(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<RpcRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcRequest> getParserForType() {
    return PARSER;
  }

  public com.dohko.core.grpc.RpcRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

