// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

public interface RpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.RpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string service = 1;</code>
   */
  java.lang.String getService();
  /**
   * <code>optional string service = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>optional string traceID = 2;</code>
   */
  java.lang.String getTraceID();
  /**
   * <code>optional string traceID = 2;</code>
   */
  com.google.protobuf.ByteString
      getTraceIDBytes();

  /**
   * <code>optional .core.RpcDataMap dataMap = 3;</code>
   */
  boolean hasDataMap();
  /**
   * <code>optional .core.RpcDataMap dataMap = 3;</code>
   */
  com.dohko.core.grpc.RpcDataMap getDataMap();
  /**
   * <code>optional .core.RpcDataMap dataMap = 3;</code>
   */
  com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder();

  /**
   * <code>optional .core.RpcHolder holder = 4;</code>
   */
  boolean hasHolder();
  /**
   * <code>optional .core.RpcHolder holder = 4;</code>
   */
  com.dohko.core.grpc.RpcHolder getHolder();
  /**
   * <code>optional .core.RpcHolder holder = 4;</code>
   */
  com.dohko.core.grpc.RpcHolderOrBuilder getHolderOrBuilder();
}
