// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

public interface RpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.RpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>optional string returnCode = 2;</code>
   */
  java.lang.String getReturnCode();
  /**
   * <code>optional string returnCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getReturnCodeBytes();

  /**
   * <code>optional string returnMsg = 3;</code>
   */
  java.lang.String getReturnMsg();
  /**
   * <code>optional string returnMsg = 3;</code>
   */
  com.google.protobuf.ByteString
      getReturnMsgBytes();

  /**
   * <code>optional string traceID = 4;</code>
   */
  java.lang.String getTraceID();
  /**
   * <code>optional string traceID = 4;</code>
   */
  com.google.protobuf.ByteString
      getTraceIDBytes();

  /**
   * <code>optional .core.RpcDataMap dataMap = 5;</code>
   */
  boolean hasDataMap();
  /**
   * <code>optional .core.RpcDataMap dataMap = 5;</code>
   */
  com.dohko.core.grpc.RpcDataMap getDataMap();
  /**
   * <code>optional .core.RpcDataMap dataMap = 5;</code>
   */
  com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder();
}
