// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

public final class RpcServiceProto {
  private RpcServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_core_RpcValue_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_RpcValue_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_core_RpcListValue_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_RpcListValue_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_core_RpcDataMap_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_RpcDataMap_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_core_RpcDataList_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_RpcDataList_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_core_RpcRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_RpcRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_core_RpcHolder_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_RpcHolder_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_core_RpcResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_RpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\004core\"\346\001\n\010RpcValue\022\026\n\014do" +
      "uble_value\030\001 \001(\001H\000\022\025\n\013float_value\030\002 \001(\002H" +
      "\000\022\026\n\014string_value\030\003 \001(\tH\000\022\024\n\nbool_value\030" +
      "\004 \001(\010H\000\022\023\n\tint_value\030\005 \001(\005H\000\022\024\n\nlong_val" +
      "ue\030\006 \001(\003H\000\022#\n\007dataMap\030\007 \001(\0132\020.core.RpcDa" +
      "taMapH\000\022%\n\010dataList\030\010 \001(\0132\021.core.RpcData" +
      "ListH\000B\006\n\004kind\"-\n\014RpcListValue\022\035\n\005value\030" +
      "\001 \003(\0132\016.core.RpcValue\"H\n\nRpcDataMap\022\033\n\003k" +
      "ey\030\001 \003(\0132\016.core.RpcValue\022\035\n\005value\030\002 \003(\0132" +
      "\016.core.RpcValue\"P\n\013RpcDataList\022\036\n\006header",
      "\030\001 \003(\0132\016.core.RpcValue\022!\n\005value\030\002 \003(\0132\022." +
      "core.RpcListValue\"r\n\nRpcRequest\022\017\n\007servi" +
      "ce\030\001 \001(\t\022\017\n\007traceID\030\002 \001(\t\022!\n\007dataMap\030\003 \001" +
      "(\0132\020.core.RpcDataMap\022\037\n\006holder\030\004 \001(\0132\017.c" +
      "ore.RpcHolder\".\n\tRpcHolder\022!\n\007dataMap\030\001 " +
      "\001(\0132\020.core.RpcDataMap\"y\n\013RpcResponse\022\017\n\007" +
      "success\030\001 \001(\010\022\022\n\nreturnCode\030\002 \001(\t\022\021\n\tret" +
      "urnMsg\030\003 \001(\t\022\017\n\007traceID\030\004 \001(\t\022!\n\007dataMap" +
      "\030\005 \001(\0132\020.core.RpcDataMap2>\n\nRpcService\0220" +
      "\n\007execute\022\020.core.RpcRequest\032\021.core.RpcRe",
      "sponse\"\000B.\n\023com.dohko.core.grpcB\017RpcServ" +
      "iceProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_core_RpcValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_RpcValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_RpcValue_descriptor,
        new java.lang.String[] { "DoubleValue", "FloatValue", "StringValue", "BoolValue", "IntValue", "LongValue", "DataMap", "DataList", "Kind", });
    internal_static_core_RpcListValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_core_RpcListValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_RpcListValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_core_RpcDataMap_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_core_RpcDataMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_RpcDataMap_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_core_RpcDataList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_core_RpcDataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_RpcDataList_descriptor,
        new java.lang.String[] { "Header", "Value", });
    internal_static_core_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_core_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_RpcRequest_descriptor,
        new java.lang.String[] { "Service", "TraceID", "DataMap", "Holder", });
    internal_static_core_RpcHolder_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_core_RpcHolder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_RpcHolder_descriptor,
        new java.lang.String[] { "DataMap", });
    internal_static_core_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_core_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_RpcResponse_descriptor,
        new java.lang.String[] { "Success", "ReturnCode", "ReturnMsg", "TraceID", "DataMap", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
