// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

/**
 * Protobuf type {@code core.RpcValue}
 */
public  final class RpcValue extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.RpcValue)
    RpcValueOrBuilder {
  // Use RpcValue.newBuilder() to construct.
  private RpcValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RpcValue() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RpcValue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 9: {
            kindCase_ = 1;
            kind_ = input.readDouble();
            break;
          }
          case 21: {
            kindCase_ = 2;
            kind_ = input.readFloat();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();
            kindCase_ = 3;
            kind_ = s;
            break;
          }
          case 32: {
            kindCase_ = 4;
            kind_ = input.readBool();
            break;
          }
          case 40: {
            kindCase_ = 5;
            kind_ = input.readInt32();
            break;
          }
          case 48: {
            kindCase_ = 6;
            kind_ = input.readInt64();
            break;
          }
          case 58: {
            com.dohko.core.grpc.RpcDataMap.Builder subBuilder = null;
            if (kindCase_ == 7) {
              subBuilder = ((com.dohko.core.grpc.RpcDataMap) kind_).toBuilder();
            }
            kind_ =
                input.readMessage(com.dohko.core.grpc.RpcDataMap.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.dohko.core.grpc.RpcDataMap) kind_);
              kind_ = subBuilder.buildPartial();
            }
            kindCase_ = 7;
            break;
          }
          case 66: {
            com.dohko.core.grpc.RpcDataList.Builder subBuilder = null;
            if (kindCase_ == 8) {
              subBuilder = ((com.dohko.core.grpc.RpcDataList) kind_).toBuilder();
            }
            kind_ =
                input.readMessage(com.dohko.core.grpc.RpcDataList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.dohko.core.grpc.RpcDataList) kind_);
              kind_ = subBuilder.buildPartial();
            }
            kindCase_ = 8;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcValue_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dohko.core.grpc.RpcValue.class, com.dohko.core.grpc.RpcValue.Builder.class);
  }

  private int kindCase_ = 0;
  private java.lang.Object kind_;
  public enum KindCase
      implements com.google.protobuf.Internal.EnumLite {
    DOUBLE_VALUE(1),
    FLOAT_VALUE(2),
    STRING_VALUE(3),
    BOOL_VALUE(4),
    INT_VALUE(5),
    LONG_VALUE(6),
    DATAMAP(7),
    DATALIST(8),
    KIND_NOT_SET(0);
    private int value = 0;
    private KindCase(int value) {
      this.value = value;
    }
    public static KindCase valueOf(int value) {
      switch (value) {
        case 1: return DOUBLE_VALUE;
        case 2: return FLOAT_VALUE;
        case 3: return STRING_VALUE;
        case 4: return BOOL_VALUE;
        case 5: return INT_VALUE;
        case 6: return LONG_VALUE;
        case 7: return DATAMAP;
        case 8: return DATALIST;
        case 0: return KIND_NOT_SET;
        default: throw new java.lang.IllegalArgumentException(
          "Value is undefined for this oneof enum.");
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public KindCase
  getKindCase() {
    return KindCase.valueOf(
        kindCase_);
  }

  public static final int DOUBLE_VALUE_FIELD_NUMBER = 1;
  /**
   * <code>optional double double_value = 1;</code>
   */
  public double getDoubleValue() {
    if (kindCase_ == 1) {
      return (java.lang.Double) kind_;
    }
    return 0D;
  }

  public static final int FLOAT_VALUE_FIELD_NUMBER = 2;
  /**
   * <code>optional float float_value = 2;</code>
   */
  public float getFloatValue() {
    if (kindCase_ == 2) {
      return (java.lang.Float) kind_;
    }
    return 0F;
  }

  public static final int STRING_VALUE_FIELD_NUMBER = 3;
  /**
   * <code>optional string string_value = 3;</code>
   */
  public java.lang.String getStringValue() {
    java.lang.Object ref = "";
    if (kindCase_ == 3) {
      ref = kind_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (kindCase_ == 3) {
        kind_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string string_value = 3;</code>
   */
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    java.lang.Object ref = "";
    if (kindCase_ == 3) {
      ref = kind_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (kindCase_ == 3) {
        kind_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOOL_VALUE_FIELD_NUMBER = 4;
  /**
   * <code>optional bool bool_value = 4;</code>
   */
  public boolean getBoolValue() {
    if (kindCase_ == 4) {
      return (java.lang.Boolean) kind_;
    }
    return false;
  }

  public static final int INT_VALUE_FIELD_NUMBER = 5;
  /**
   * <code>optional int32 int_value = 5;</code>
   */
  public int getIntValue() {
    if (kindCase_ == 5) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }

  public static final int LONG_VALUE_FIELD_NUMBER = 6;
  /**
   * <code>optional int64 long_value = 6;</code>
   */
  public long getLongValue() {
    if (kindCase_ == 6) {
      return (java.lang.Long) kind_;
    }
    return 0L;
  }

  public static final int DATAMAP_FIELD_NUMBER = 7;
  /**
   * <code>optional .core.RpcDataMap dataMap = 7;</code>
   */
  public com.dohko.core.grpc.RpcDataMap getDataMap() {
    if (kindCase_ == 7) {
       return (com.dohko.core.grpc.RpcDataMap) kind_;
    }
    return com.dohko.core.grpc.RpcDataMap.getDefaultInstance();
  }
  /**
   * <code>optional .core.RpcDataMap dataMap = 7;</code>
   */
  public com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder() {
    if (kindCase_ == 7) {
       return (com.dohko.core.grpc.RpcDataMap) kind_;
    }
    return com.dohko.core.grpc.RpcDataMap.getDefaultInstance();
  }

  public static final int DATALIST_FIELD_NUMBER = 8;
  /**
   * <code>optional .core.RpcDataList dataList = 8;</code>
   */
  public com.dohko.core.grpc.RpcDataList getDataList() {
    if (kindCase_ == 8) {
       return (com.dohko.core.grpc.RpcDataList) kind_;
    }
    return com.dohko.core.grpc.RpcDataList.getDefaultInstance();
  }
  /**
   * <code>optional .core.RpcDataList dataList = 8;</code>
   */
  public com.dohko.core.grpc.RpcDataListOrBuilder getDataListOrBuilder() {
    if (kindCase_ == 8) {
       return (com.dohko.core.grpc.RpcDataList) kind_;
    }
    return com.dohko.core.grpc.RpcDataList.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kindCase_ == 1) {
      output.writeDouble(
          1, (double)((java.lang.Double) kind_));
    }
    if (kindCase_ == 2) {
      output.writeFloat(
          2, (float)((java.lang.Float) kind_));
    }
    if (kindCase_ == 3) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, kind_);
    }
    if (kindCase_ == 4) {
      output.writeBool(
          4, (boolean)((java.lang.Boolean) kind_));
    }
    if (kindCase_ == 5) {
      output.writeInt32(
          5, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 6) {
      output.writeInt64(
          6, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 7) {
      output.writeMessage(7, (com.dohko.core.grpc.RpcDataMap) kind_);
    }
    if (kindCase_ == 8) {
      output.writeMessage(8, (com.dohko.core.grpc.RpcDataList) kind_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kindCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            1, (double)((java.lang.Double) kind_));
    }
    if (kindCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(
            2, (float)((java.lang.Float) kind_));
    }
    if (kindCase_ == 3) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, kind_);
    }
    if (kindCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            4, (boolean)((java.lang.Boolean) kind_));
    }
    if (kindCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            5, (int)((java.lang.Integer) kind_));
    }
    if (kindCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            6, (long)((java.lang.Long) kind_));
    }
    if (kindCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.dohko.core.grpc.RpcDataMap) kind_);
    }
    if (kindCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (com.dohko.core.grpc.RpcDataList) kind_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static com.dohko.core.grpc.RpcValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dohko.core.grpc.RpcValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dohko.core.grpc.RpcValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.dohko.core.grpc.RpcValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.dohko.core.grpc.RpcValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.dohko.core.grpc.RpcValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.dohko.core.grpc.RpcValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dohko.core.grpc.RpcValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code core.RpcValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.RpcValue)
      com.dohko.core.grpc.RpcValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dohko.core.grpc.RpcValue.class, com.dohko.core.grpc.RpcValue.Builder.class);
    }

    // Construct using com.dohko.core.grpc.RpcValue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      kindCase_ = 0;
      kind_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dohko.core.grpc.RpcServiceProto.internal_static_core_RpcValue_descriptor;
    }

    public com.dohko.core.grpc.RpcValue getDefaultInstanceForType() {
      return com.dohko.core.grpc.RpcValue.getDefaultInstance();
    }

    public com.dohko.core.grpc.RpcValue build() {
      com.dohko.core.grpc.RpcValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dohko.core.grpc.RpcValue buildPartial() {
      com.dohko.core.grpc.RpcValue result = new com.dohko.core.grpc.RpcValue(this);
      if (kindCase_ == 1) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 2) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 3) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 4) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 5) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 6) {
        result.kind_ = kind_;
      }
      if (kindCase_ == 7) {
        if (dataMapBuilder_ == null) {
          result.kind_ = kind_;
        } else {
          result.kind_ = dataMapBuilder_.build();
        }
      }
      if (kindCase_ == 8) {
        if (dataListBuilder_ == null) {
          result.kind_ = kind_;
        } else {
          result.kind_ = dataListBuilder_.build();
        }
      }
      result.kindCase_ = kindCase_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dohko.core.grpc.RpcValue) {
        return mergeFrom((com.dohko.core.grpc.RpcValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dohko.core.grpc.RpcValue other) {
      if (other == com.dohko.core.grpc.RpcValue.getDefaultInstance()) return this;
      switch (other.getKindCase()) {
        case DOUBLE_VALUE: {
          setDoubleValue(other.getDoubleValue());
          break;
        }
        case FLOAT_VALUE: {
          setFloatValue(other.getFloatValue());
          break;
        }
        case STRING_VALUE: {
          kindCase_ = 3;
          kind_ = other.kind_;
          onChanged();
          break;
        }
        case BOOL_VALUE: {
          setBoolValue(other.getBoolValue());
          break;
        }
        case INT_VALUE: {
          setIntValue(other.getIntValue());
          break;
        }
        case LONG_VALUE: {
          setLongValue(other.getLongValue());
          break;
        }
        case DATAMAP: {
          mergeDataMap(other.getDataMap());
          break;
        }
        case DATALIST: {
          mergeDataList(other.getDataList());
          break;
        }
        case KIND_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dohko.core.grpc.RpcValue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dohko.core.grpc.RpcValue) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int kindCase_ = 0;
    private java.lang.Object kind_;
    public KindCase
        getKindCase() {
      return KindCase.valueOf(
          kindCase_);
    }

    public Builder clearKind() {
      kindCase_ = 0;
      kind_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>optional double double_value = 1;</code>
     */
    public double getDoubleValue() {
      if (kindCase_ == 1) {
        return (java.lang.Double) kind_;
      }
      return 0D;
    }
    /**
     * <code>optional double double_value = 1;</code>
     */
    public Builder setDoubleValue(double value) {
      kindCase_ = 1;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double double_value = 1;</code>
     */
    public Builder clearDoubleValue() {
      if (kindCase_ == 1) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>optional float float_value = 2;</code>
     */
    public float getFloatValue() {
      if (kindCase_ == 2) {
        return (java.lang.Float) kind_;
      }
      return 0F;
    }
    /**
     * <code>optional float float_value = 2;</code>
     */
    public Builder setFloatValue(float value) {
      kindCase_ = 2;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional float float_value = 2;</code>
     */
    public Builder clearFloatValue() {
      if (kindCase_ == 2) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>optional string string_value = 3;</code>
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = "";
      if (kindCase_ == 3) {
        ref = kind_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (kindCase_ == 3) {
          kind_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string string_value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = "";
      if (kindCase_ == 3) {
        ref = kind_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (kindCase_ == 3) {
          kind_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string string_value = 3;</code>
     */
    public Builder setStringValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  kindCase_ = 3;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string string_value = 3;</code>
     */
    public Builder clearStringValue() {
      if (kindCase_ == 3) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional string string_value = 3;</code>
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      kindCase_ = 3;
      kind_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>optional bool bool_value = 4;</code>
     */
    public boolean getBoolValue() {
      if (kindCase_ == 4) {
        return (java.lang.Boolean) kind_;
      }
      return false;
    }
    /**
     * <code>optional bool bool_value = 4;</code>
     */
    public Builder setBoolValue(boolean value) {
      kindCase_ = 4;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool bool_value = 4;</code>
     */
    public Builder clearBoolValue() {
      if (kindCase_ == 4) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>optional int32 int_value = 5;</code>
     */
    public int getIntValue() {
      if (kindCase_ == 5) {
        return (java.lang.Integer) kind_;
      }
      return 0;
    }
    /**
     * <code>optional int32 int_value = 5;</code>
     */
    public Builder setIntValue(int value) {
      kindCase_ = 5;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 int_value = 5;</code>
     */
    public Builder clearIntValue() {
      if (kindCase_ == 5) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>optional int64 long_value = 6;</code>
     */
    public long getLongValue() {
      if (kindCase_ == 6) {
        return (java.lang.Long) kind_;
      }
      return 0L;
    }
    /**
     * <code>optional int64 long_value = 6;</code>
     */
    public Builder setLongValue(long value) {
      kindCase_ = 6;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 long_value = 6;</code>
     */
    public Builder clearLongValue() {
      if (kindCase_ == 6) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder> dataMapBuilder_;
    /**
     * <code>optional .core.RpcDataMap dataMap = 7;</code>
     */
    public com.dohko.core.grpc.RpcDataMap getDataMap() {
      if (dataMapBuilder_ == null) {
        if (kindCase_ == 7) {
          return (com.dohko.core.grpc.RpcDataMap) kind_;
        }
        return com.dohko.core.grpc.RpcDataMap.getDefaultInstance();
      } else {
        if (kindCase_ == 7) {
          return dataMapBuilder_.getMessage();
        }
        return com.dohko.core.grpc.RpcDataMap.getDefaultInstance();
      }
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 7;</code>
     */
    public Builder setDataMap(com.dohko.core.grpc.RpcDataMap value) {
      if (dataMapBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        dataMapBuilder_.setMessage(value);
      }
      kindCase_ = 7;
      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 7;</code>
     */
    public Builder setDataMap(
        com.dohko.core.grpc.RpcDataMap.Builder builderForValue) {
      if (dataMapBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        dataMapBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 7;
      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 7;</code>
     */
    public Builder mergeDataMap(com.dohko.core.grpc.RpcDataMap value) {
      if (dataMapBuilder_ == null) {
        if (kindCase_ == 7 &&
            kind_ != com.dohko.core.grpc.RpcDataMap.getDefaultInstance()) {
          kind_ = com.dohko.core.grpc.RpcDataMap.newBuilder((com.dohko.core.grpc.RpcDataMap) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 7) {
          dataMapBuilder_.mergeFrom(value);
        }
        dataMapBuilder_.setMessage(value);
      }
      kindCase_ = 7;
      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 7;</code>
     */
    public Builder clearDataMap() {
      if (dataMapBuilder_ == null) {
        if (kindCase_ == 7) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 7) {
          kindCase_ = 0;
          kind_ = null;
        }
        dataMapBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 7;</code>
     */
    public com.dohko.core.grpc.RpcDataMap.Builder getDataMapBuilder() {
      return getDataMapFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 7;</code>
     */
    public com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder() {
      if ((kindCase_ == 7) && (dataMapBuilder_ != null)) {
        return dataMapBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 7) {
          return (com.dohko.core.grpc.RpcDataMap) kind_;
        }
        return com.dohko.core.grpc.RpcDataMap.getDefaultInstance();
      }
    }
    /**
     * <code>optional .core.RpcDataMap dataMap = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder> 
        getDataMapFieldBuilder() {
      if (dataMapBuilder_ == null) {
        if (!(kindCase_ == 7)) {
          kind_ = com.dohko.core.grpc.RpcDataMap.getDefaultInstance();
        }
        dataMapBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.dohko.core.grpc.RpcDataMap, com.dohko.core.grpc.RpcDataMap.Builder, com.dohko.core.grpc.RpcDataMapOrBuilder>(
                (com.dohko.core.grpc.RpcDataMap) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 7;
      onChanged();;
      return dataMapBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcDataList, com.dohko.core.grpc.RpcDataList.Builder, com.dohko.core.grpc.RpcDataListOrBuilder> dataListBuilder_;
    /**
     * <code>optional .core.RpcDataList dataList = 8;</code>
     */
    public com.dohko.core.grpc.RpcDataList getDataList() {
      if (dataListBuilder_ == null) {
        if (kindCase_ == 8) {
          return (com.dohko.core.grpc.RpcDataList) kind_;
        }
        return com.dohko.core.grpc.RpcDataList.getDefaultInstance();
      } else {
        if (kindCase_ == 8) {
          return dataListBuilder_.getMessage();
        }
        return com.dohko.core.grpc.RpcDataList.getDefaultInstance();
      }
    }
    /**
     * <code>optional .core.RpcDataList dataList = 8;</code>
     */
    public Builder setDataList(com.dohko.core.grpc.RpcDataList value) {
      if (dataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        dataListBuilder_.setMessage(value);
      }
      kindCase_ = 8;
      return this;
    }
    /**
     * <code>optional .core.RpcDataList dataList = 8;</code>
     */
    public Builder setDataList(
        com.dohko.core.grpc.RpcDataList.Builder builderForValue) {
      if (dataListBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        dataListBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 8;
      return this;
    }
    /**
     * <code>optional .core.RpcDataList dataList = 8;</code>
     */
    public Builder mergeDataList(com.dohko.core.grpc.RpcDataList value) {
      if (dataListBuilder_ == null) {
        if (kindCase_ == 8 &&
            kind_ != com.dohko.core.grpc.RpcDataList.getDefaultInstance()) {
          kind_ = com.dohko.core.grpc.RpcDataList.newBuilder((com.dohko.core.grpc.RpcDataList) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 8) {
          dataListBuilder_.mergeFrom(value);
        }
        dataListBuilder_.setMessage(value);
      }
      kindCase_ = 8;
      return this;
    }
    /**
     * <code>optional .core.RpcDataList dataList = 8;</code>
     */
    public Builder clearDataList() {
      if (dataListBuilder_ == null) {
        if (kindCase_ == 8) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 8) {
          kindCase_ = 0;
          kind_ = null;
        }
        dataListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .core.RpcDataList dataList = 8;</code>
     */
    public com.dohko.core.grpc.RpcDataList.Builder getDataListBuilder() {
      return getDataListFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .core.RpcDataList dataList = 8;</code>
     */
    public com.dohko.core.grpc.RpcDataListOrBuilder getDataListOrBuilder() {
      if ((kindCase_ == 8) && (dataListBuilder_ != null)) {
        return dataListBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 8) {
          return (com.dohko.core.grpc.RpcDataList) kind_;
        }
        return com.dohko.core.grpc.RpcDataList.getDefaultInstance();
      }
    }
    /**
     * <code>optional .core.RpcDataList dataList = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.dohko.core.grpc.RpcDataList, com.dohko.core.grpc.RpcDataList.Builder, com.dohko.core.grpc.RpcDataListOrBuilder> 
        getDataListFieldBuilder() {
      if (dataListBuilder_ == null) {
        if (!(kindCase_ == 8)) {
          kind_ = com.dohko.core.grpc.RpcDataList.getDefaultInstance();
        }
        dataListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.dohko.core.grpc.RpcDataList, com.dohko.core.grpc.RpcDataList.Builder, com.dohko.core.grpc.RpcDataListOrBuilder>(
                (com.dohko.core.grpc.RpcDataList) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 8;
      onChanged();;
      return dataListBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:core.RpcValue)
  }

  // @@protoc_insertion_point(class_scope:core.RpcValue)
  private static final com.dohko.core.grpc.RpcValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dohko.core.grpc.RpcValue();
  }

  public static com.dohko.core.grpc.RpcValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcValue>
      PARSER = new com.google.protobuf.AbstractParser<RpcValue>() {
    public RpcValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new RpcValue(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<RpcValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcValue> getParserForType() {
    return PARSER;
  }

  public com.dohko.core.grpc.RpcValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

