// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.dohko.core.grpc;

public interface RpcValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.RpcValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double double_value = 1;</code>
   */
  double getDoubleValue();

  /**
   * <code>optional float float_value = 2;</code>
   */
  float getFloatValue();

  /**
   * <code>optional string string_value = 3;</code>
   */
  java.lang.String getStringValue();
  /**
   * <code>optional string string_value = 3;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>optional bool bool_value = 4;</code>
   */
  boolean getBoolValue();

  /**
   * <code>optional int32 int_value = 5;</code>
   */
  int getIntValue();

  /**
   * <code>optional int64 long_value = 6;</code>
   */
  long getLongValue();

  /**
   * <code>optional .core.RpcDataMap dataMap = 7;</code>
   */
  com.dohko.core.grpc.RpcDataMap getDataMap();
  /**
   * <code>optional .core.RpcDataMap dataMap = 7;</code>
   */
  com.dohko.core.grpc.RpcDataMapOrBuilder getDataMapOrBuilder();

  /**
   * <code>optional .core.RpcDataList dataList = 8;</code>
   */
  com.dohko.core.grpc.RpcDataList getDataList();
  /**
   * <code>optional .core.RpcDataList dataList = 8;</code>
   */
  com.dohko.core.grpc.RpcDataListOrBuilder getDataListOrBuilder();

  public com.dohko.core.grpc.RpcValue.KindCase getKindCase();
}
